"""Dataset construction and behavior-cloning training.

Demo rollouts are generated by the oracle; every step becomes a training sample
(image rendered at the episode's yaw, oracle delta). The same dataset serves both
heads: targets are converted per-head (base delta vs camera-frame delta).

Images are stored as uint8 to bound memory; converted to float on batch load.
"""
from __future__ import annotations

import time
import numpy as np
import torch
from torch import nn

import blob_world as bw
from models import Policy


class DemoDataset:
    """Rendered uint8 images + base-frame targets + per-sample yaw."""

    def __init__(self, imgs_u8: np.ndarray, deltas: np.ndarray, yaws: np.ndarray):
        self.imgs = torch.from_numpy(np.ascontiguousarray(imgs_u8))  # N,H,W,C uint8
        self.deltas = torch.from_numpy(deltas.astype(np.float32))    # N,3 base deltas
        self.yaws = torch.from_numpy(yaws.astype(np.float32))        # N,
        self.n = len(imgs_u8)


def build_dataset(yaws: list[float], n_episodes: int, seed: int) -> DemoDataset:
    """Generate oracle demos and render every step's image at the episode's yaw.

    Returns (imgs_u8 (N,64,64,3), base deltas (N,3), per-sample yaws (N,)).
    """
    rng = np.random.default_rng(seed)
    states_all, deltas_all, yaws_all = [], [], []
    t0 = time.time()
    for i in range(n_episodes):
        yaw = float(rng.choice(yaws))
        states, deltas, tgt = bw.gen_episode(rng)
        # render needs the target for the red blob; store per-step (ee, tgt) pairs
        for st in states:
            states_all.append(np.concatenate([st, tgt]))
        deltas_all.append(deltas)
        yaws_all.append([yaw] * len(states))
        if (i + 1) % 1000 == 0:
            print(f"  demos {i+1}/{n_episodes} ({time.time()-t0:.0f}s)", flush=True)
    states_all = np.asarray(states_all)   # (N,6): ee then tgt
    deltas_all = np.concatenate(deltas_all)
    yaws_all = np.concatenate(yaws_all)
    n = len(states_all)
    print(f"  total samples {n}, rendering...", flush=True)
    imgs = np.empty((n, bw.IMG, bw.IMG, 3), dtype=np.uint8)
    t0 = time.time()
    for k in range(n):
        ee = states_all[k, :3]
        tgt = states_all[k, 3:]
        imgs[k] = (bw.render(ee, tgt, yaws_all[k]) * 255).astype(np.uint8)
        if (k + 1) % 10000 == 0:
            print(f"  rendered {k+1}/{n} ({time.time()-t0:.0f}s)", flush=True)
    return DemoDataset(imgs, deltas_all, yaws_all)


def train(dataset: DemoDataset, head: str, epochs: int, lr: float, batch_size: int,
          seed: int, out_path: str) -> Policy:
    """BC-train a policy. head in {'base','cam'}.

    cam target = R_cb(yaw) @ delta_base -- an isometry, so the MSE magnitude is
    identical to the base head; only the output coordinate frame differs.
    """
    torch.manual_seed(seed)
    rng = np.random.default_rng(seed)
    model = Policy(3)
    opt = torch.optim.Adam(model.parameters(), lr=lr, weight_decay=1e-5)
    lossf = nn.MSELoss()
    delta_t = dataset.deltas
    yaw_t = dataset.yaws
    n = dataset.n
    Rb0 = torch.tensor(bw._R0, dtype=torch.float32)  # canonical R_bc(0)
    # precompute R_cb for each distinct yaw once (batch vectorized)
    yaw_vals = torch.unique(yaw_t)
    R_cb_cache = torch.stack(
        [(torch.tensor(bw.rz(float(y)), dtype=torch.float32) @ Rb0).T for y in yaw_vals])
    yaw_ids = ((yaw_t[:, None] == yaw_vals[None, :]) * torch.arange(len(yaw_vals))).sum(1).long()
    print(f"[{head}] train on {n} samples, {epochs} epochs", flush=True)
    t0 = time.time()
    for ep in range(epochs):
        model.train()
        perm = rng.permutation(n)
        total, cnt = 0.0, 0
        for i in range(0, n, batch_size):
            idx = perm[i:i + batch_size]
            x = dataset.imgs[idx].permute(0, 3, 1, 2).float() / 255.0
            d_b = delta_t[idx]
            if head == 'cam':
                R_cb = R_cb_cache[yaw_ids[idx]]
                target = torch.einsum('bij,bj->bi', R_cb, d_b)
            else:
                target = d_b
            pred = model(x)
            loss = lossf(pred, target)
            opt.zero_grad()
            loss.backward()
            opt.step()
            total += loss.item() * len(idx)
            cnt += len(idx)
        if (ep + 1) % 5 == 0 or ep == epochs - 1:
            print(f"  [{head}] epoch {ep+1}/{epochs} mse={total/cnt:.6f} ({time.time()-t0:.0f}s)", flush=True)
    torch.save(model.state_dict(), out_path)
    print(f"[{head}] saved {out_path}", flush=True)
    return model
